sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:https://oss-cn-beijing.aliyuncs.com}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIYUN_OSS_BUCKET:web-test-bai}
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: ${WECHAT_APPID:}
    secret: ${WECHAT_SECRET:}
